model_dir: "models/"
dataset_dir: "data/"
plot_dir: "efficientnet_svm/plots/"
num_classes: 16
image_size: 224
learning_rate: 0.001
batch_size: 32
k_fold: 5
num_epoch: 100

classes:
  dir: "classes/"
  file_name: "classes.txt"

checkpoint:
  dir: "efficientnet_svm/checkpoints/"
  name: "checkpoint.pth"

backbone:
  dir: "efficientnet_svm/backbone/"

classifier:
  dir: "efficientnet_svm/classifier/"
  
training_log:
  dir: "efficientnet_svm/logs/"
  name: "training_log.csv"

fold_results:
  dir: "efficientnet_svm/fold_results/"
  backbone: "backbone_fold_results.csv"
  classifier: "svm_fold_results.csv"

classification_report:
  dir: "efficientnet_svm/classification_reports/"
  backbone: "backbone_classification_report.json"
  svm: "svm_classification_report.json"