model_dir: './models/'
checkpoint_dir: './checkpoints/'
checkpoint_name: 'checkpoint.pth'
backbone_dir: './backbone/'
backbone_name: 'backbone.pth'
classifier_dir: './classifier/'
classifier_name: 'classifier.joblib'
dataset_dir: './data/'
training_log_dir: './logs/'
training_log_name: 'training_log.csv'
classification_report_dir: './classification_reports/'
num_classes: 16
image_size: 224
learning_rate: 0.001
batch_size: 32
warmup_epochs: 5
num_epoch: 50